### ISSUE TITLE
Ergebnis ändern ohne Abstimmung neu zu starten

### ISSUE THREAD

**Issue by tleilax** [luniki/CliqrPlugin#102]
Bei uns kam folgende Frage rein, die ich mal so als Frage/Feature Request durchreiche:

> ich verwende Cliqr um den Fortschritt in praktischen Übungen in größeren Gruppen zu erfragen. Dafür wäre es extrem praktisch, wenn die Abstimmenden ihr Ergebnis (mehrfach) ändern könnten, ohne das ich die Abstimmung neu starten muss. Geht/ginge so etwas?

**Comment by luniki** [comment]
Dazu habe ich ein paar Fragen:

* Soll der Dozent dann das Ergebnis schon während des Abstimmungsprozesses sehen können?
* Bedeutet das, dass der Dozent mehrere Fragen gleichzeitig zur Abstimmung stellen möchte?

**Comment by tleilax** [comment]
Antwort vom Lehrenden, der die Anfrage gestellt hat:

> ja, meine Idee war, dass der Dozent 1 Frage stellt und das Ergebnis während der Abstimmung bereits einsehen kann (ohne das die Umfrage beendet werden muss).
> 
> In diesem Fall wäre es zudem interessant, wenn die Teilnehmer ihre Antwort (mehrfach) korrigieren könnten. Bisher erfordert dies ein stoppen und erneutes Starten der Umfrage.

**Comment by luniki** [comment]
Ich werde das nächste Woche mal in Ruhe mit Nico durchsprechen.

**Comment by luniki** [comment]
Ohne die Frage neu zu starten, wird das erstmal nichts. Möglicherweise ist das sowieso eher ein Fall für ein anderes Plugin.
