### ISSUE TITLE
Fehler beim Bearbeiten von MC-Fragen

### ISSUE THREAD

**Issue by nimuelle** [luniki/CliqrPlugin#134]
1. Multiple-Choice-Frage mit Antworten erstellen und speichern
2. Frage bearbeiten und beliebigen Antworttext ändern / Antwort
entfernen / Antwort hinzufügen und dann speichern
3. alle unter 2. ausgeführten Schritte wurden nicht gespeichert

**Comment by nimuelle** [comment]
@luniki

**Comment by luniki** [comment]
Ich setz mich dran
