### ISSUE TITLE
Fehler in Firefox 41

### ISSUE THREAD

**Issue by tleilax** [luniki/CliqrPlugin#63]
Beim Aufruf von bsow. `plugins.php/cliqrplugin/poll/8f91dff542fcbfbdbd28ac1ae69cea51` bricht das JS mit folgender Fehlermeldung ab:

```
Error: Permission denied to access property "length"
http://127.0.0.1/studip/uol-3.1/plugins_packages/elan-ev/CliqrPlugin/assets/js/vendor/jquery-1.8.2.js?bust=1443781671050
Line 679
```
Ich habe schon versucht, da irgendwas zu finden, aber bin leider nicht fündig geworden.

Im Chrome geht alles.

**Comment by luniki** [comment]
Ich hab hier gerade nur einen 40 und 43. In beiden sehe ich keinen Fehler, wenn ich folgende URL aufrufe:

https://develop.studip.de/studip/plugins.php/cliqrplugin/poll/d975fa53d112b857982becc182331971?

**Comment by tleilax** [comment]
Im 43.0a2 bekomme ich auch keinen Fehler, im Firefox 41 besteht der Fehler aber weiterhin:

<img width="1279" alt="screenshot 2015-10-05 09 50 39" src="https://cloud.githubusercontent.com/assets/130213/10275353/147762be-6b47-11e5-8324-687d4be915b7.png">

**Comment by luniki** [comment]
Ich hab mir jetzt unter Linux Mint einen Firefox 41.0.1 heruntergeladen und die oben genannte URL ausprobiert. Deinen Fehler erhalte ich da aber nicht.
Wenn mein Kollege nachher da ist, werde ich das mal unter Mac OS X ausprobieren.

**Comment by tleilax** [comment]
Scheint kein Plugin-spezifisches Problem zu sein sondern eher ein Problem eines Addons im Firefox
