### ISSUE TITLE
PHP7 Warning

### ISSUE THREAD

**Issue by nimuelle** [luniki/CliqrPlugin#81]
Weil es schnell geht ;-)

Warning: Declaration of Cliqr\CliqrStudipController::url_for($to) should be compatible with StudipController::url_for($to = '') in /var/www/studip_3.5/public/plugins_packages/elan-ev/CliqrPlugin/app/controllers/cliqr_studip_controller.php on line 0

**Comment by luniki** [comment]
fixed in  e3e0dfe
